### ISSUE TITLE
我在学习angular2 请帮帮我 

### ISSUE THREAD

**Issue by jiatongwu** [angular-programming/angular2-contacts-demo#3]
wus-iMac:angular2-contacts-demo wu$ ng serve
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest" 

^C
wus-iMac:angular2-contacts-demo wu$ npm install --save-dev @angular/cli@latest

wus-iMac:angular2-contacts-demo wu$ ng serve
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (/Volumes/bak/main-workspace/angular2/angular2-contacts-demo/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/bak/main-workspace/angular2/angular2-contacts-demo/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
wus-iMac:angular2-contacts-demo wu$ npm list typescript
contact@1.0.0 /Volumes/bak/main-workspace/angular2/angular2-contacts-demo
├─┬ @angular/cli@1.3.0
│ ├─┬ @angular-devkit/build-optimizer@0.0.13
│ │ └── typescript@2.4.2 
│ ├── UNMET PEER DEPENDENCY enhanced-resolve@^3.1.0
│ └── UNMET PEER DEPENDENCY webpack@3.4.1
└── UNMET PEER DEPENDENCY typescript@2.0.0

npm ERR! peer dep missing: typescript@^2.0.2, required by @ngtools/webpack@1.6.0
npm ERR! peer dep missing: webpack@^2.2.0 || ^3.0.0, required by @ngtools/webpack@1.6.0
npm ERR! peer dep missing: webpack@^3.1.0, required by extract-text-webpack-plugin@3.0.0
npm ERR! peer dep missing: webpack@^2.0.0 || ^3.0.0, required by less-loader@4.0.5
npm ERR! peer dep missing: webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0, required by sass-loader@6.0.6
npm ERR! peer dep missing: enhanced-resolve@^3.1.0, required by @ngtools/webpack@1.6.0
 wus-iMac:angular2-contacts-demo wu$

**Comment by ghost** [comment]
你好，该项目是去年早起的项目，基于 webpack 构建的，并不支持 ng 命令。已经有新的版本是基于 Angular CLI 构建的，可以参照这个版本来学习：https://github.com/angular-programming/angular-contacts-demo

**Comment by jiatongwu** [comment]
非常感谢
